package:
  name: datamining
  version: 0.0.2

source:
  path: .

build:
  number: 2

requirements:
  build:
    - python
    - Cython
    - numpy
    - setuptools
  run:
    - python
    - numpy

about:
  summary: Datamining is a package for data mining - what a surprise. It aims to implement several clustering, subspace clustering, and projected clustering algorithms for both the CPU and GPU.

home: https://github.com/mrjakobdk/datamining