{% set data = load_setup_py_data() %}

package:
  name: datamining
  version: 0.0.5

source:
  path: .

build:
  number: 5

requirements:
  build:
    - python
    - Cython
    - numpy
    - setuptools
  run:
    - python
    - numpy

about:
  summary: Datamining is a package for data mining - what a surprise. It aims to implement several clustering, subspace clustering, and projected clustering algorithms for both the CPU and GPU. Documentation is found at mrjakob.dk/datamining/docs

home: https://github.com/mrjakobdk/datamining